server:
  port: 20000
  error:
    include-message: always

spring:
  application:
    name: coupon-template-serv
    datasource:
      username: root
      password: root # Note(zhangjianhui03): need modify
      url: x # Note(zhangjianhui03): need modify
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: GeekbangCouponHikari
        connection-timeout: 5000
        idle-timeout: 30000
        maximum-pool-size: 10
        minimum-idle: 5
        max-lifetime: 60000
        auto-commit: true
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate.format_sql: true
        hibernate.show_sql: true
      open_in_view: false

logging:
  level:
    com.broadview.coupon: debug
