server:
  port: 20002
  error:
    include-message: always

spring:
  application:
    name: coupon-calculation-serv
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: coupon-template-serv
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        metadata:
          mydata: abc
        naming-load-cache-at-start: false
        cluster-name: Cluster-A
        namespace: dev
        group: myGroup
        register-enabled: true
        watch:
          enabled: true
        watch-delay: 30000

logging:
  level:
    com.broadview.coupon: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"